### ISSUE TITLE
formal release or tag for 0.2.5

### ISSUE THREAD

**Issue by osfans** [s-yata/marisa-trie#10]

**Comment by escondida** [comment]
Hey, thanks for marisa! It's a neat library.

Since it's used by various useful libaries such as [librime](https://github.com/rime/librime) and [libkkc](https://github.com/rime/librime), and since code.google.com isn't going to keep their archive around forever, is there any chance of making a formal release tag? That way, github will provide release tarballs for the project automagically.

Thanks again!

**Comment by s-yata** [comment]
Sorry for my very very late reaction.

I've added a tag `v0.2.5`.

https://github.com/s-yata/marisa-trie/releases/tag/v0.2.5

**Comment by escondida** [comment]
Thanks, s-yata!

**Comment by s-yata** [comment]
I've added a release v0.2.5.

https://github.com/s-yata/marisa-trie/releases/tag/v0.2.5

marisa-0.2.5.tar.gz is an archive generated by `make dist`.
